git:
  pagers:
    - pager: delta --dark --paging=never
gui:
  showIcons: false
  theme:
    activeBorderColor:
    - '#fab387'
    inactiveBorderColor:
    - '#89b4fa'
    lightTheme: false
    selectedLineBgColor:
    - '#45475a'
